### ISSUE TITLE
Clustering results are discarded - new release

### ISSUE THREAD

**Issue by AGrosserHH** [YaleDHLab/pix-plot#104]
HI all, after the new release of pixplot 17 days ago I was wondering how the display the number of images / images names in a cluster.
The code from posts in the past (#65, #72) do not work anymore. Thanks again for this!

Would be much appreciated!

Cheers,
Andi

**Comment by duhaime** [comment]
Thanks for reaching out @AGrosserHH ! As you noticed, we've moved to a python module setup, but it's easy enough to find and modify the module to get this information.

First things first, one should find where the pixplot module code is. To do that, you should be able to type `python` and hit enter in a terminal. That will drop you into the Python interpreter (you'll know you're in the interpreter if you see `>>>` as your terminal prompt).

Once you're in the interpreter, try typing:

```python
import pixplot
print(pixplot.__file__)
```

That should tell you the path like:

```
.../pixplot-{version}/pixplot/__init__.py
```

If you navigate to the folder that contains that __init__.py file, you should see another file `pixplot.py`; that's the file we'll want to change to display the info you discuss above.

Once you open up that file, you'll see a function `get_centroids()`. In that function, there's a variable `z` with an attribute`labels_` that contains the cluster assignments of each input image in order (so the ith value in `z.labels_` is the cluster id for the ith image in `kwargs['image_paths']`). To get the number of images in each cluster and the names of the images in each cluster, one can therefore add (somewhere after `z` is fully populated):

```python
cluster_map = defaultdict(list)
  for idx, i in enumerate(z.labels_):
    cluster_map[i].append(kwargs['image_paths'][idx])
  for i in cluster_map:
    print(' * cluster {} has {} images: {}'.format(i, len(cluster_map[i]), cluster_map[i]), '\n')
```

I hope that helps! I'm happy to follow up if you try to add this and get stuck...

**Comment by duhaime** [comment]
@AGrosserHH I'm going to close this issue for now, but please feel free to follow up if you have any troubles!
