### ISSUE TITLE
Install error: Could not find tensorflow version

### ISSUE THREAD

**Issue by cengel** [YaleDHLab/pix-plot#111]
`pip install pixplot`

gave me this:

`ERROR: Could not find a version that satisfies the requirement tensorflow<=2.0.0,>=1.14.0 (from pixplot) (from versions: 2.2.0rc1, 2.2.0rc2)`
`ERROR: No matching distribution found for tensorflow<=2.0.0,>=1.14.0 (from pixplot)`

As a workaround I switched to python 3.6 (from 3.8) and the install worked.

**Comment by duhaime** [comment]
Huh, that's interesting! In fact there's evidently no version of tensorflow for Python 3.8 yet:

```
(3.8) Duhaime:~ doug$ pip install tensorflow
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```

[There's an issue in the tensorflow issue tracker following 3.8 support](https://github.com/tensorflow/tensorflow/issues/33374), and it seems a release is imminent. In any event, thanks for the heads up!

**Comment by duhaime** [comment]
@cengel if it'd be alright, it might make sense to close this as there's nothing this library can do about Tensorflow support for Python 3.8. I'm glad you brought this to our attention though!

**Comment by cengel** [comment]
hm.. this all seems to be a little in flux... and as far as I understand it, the problem is also that your setup script does not allow for TF versions higher than 2.0.

I just ran what seems to be a sucessful pixplot install with python 3.8, though I have not had a chance to test if it works as expected. I cloned your repo and installed locally, changing your `setyup.py` in line 38 from 

` 'tensorflow>=1.14.0,<=2.0.0',`
to
`'tensorflow>=1.14.0',`

(I additionally needed to install cython before installing pixplot.)

My Python version is 3.8.2
It seems to install [tensorflow 2.2.0rc3](https://github.com/tensorflow/tensorflow/releases/tag/v2.2.0-rc3), which was just pre-released a few hours ago. 

So it appears that even once the new TF version is officially released, the install might still not work?

**Comment by duhaime** [comment]
@cengel many thanks for your follow up. Yes, it appears that even the most recent Tensorflow release still does not support Python 3.8...

I think until Tensorflow has support for Python 3.8 or 3.9, the simplest solution is to switch to an earlier Python version when doing Tensorflow-related work. If you [install Anaconda](https://www.anaconda.com/distribution/), you could create a virtual environment using e.g. Python 3.6:

```
conda create --name 3.6 python=3.6
```
Once you activate that environment, you should be able to

```
pip install pixplot
```

If you give that a shot, I'd be happy to assist if you hit any bumps!

**Comment by cengel** [comment]
Thanks @duhaime - this is exactly what I did as I said in my first comment. 
> As a workaround I switched to python 3.6 (from 3.8) and the install worked

**Comment by duhaime** [comment]
Ah, you're quite right! That's likely the easiest way forward...
