### ISSUE TITLE
Keras dependancy issue

### ISSUE THREAD

**Issue by marcheseV** [YaleDHLab/pix-plot#120]
Hi, 

I'm really enjoying this library - Very good work.

However, as of yesterday an issue popped up with a clean install of pixplot. Specifically, I'm getting this error:

`ModuleNotFoundError: No module named 'keras.backend.tensorflow_backend'; 'keras.backend' is not a package` 

I've traced this issue to the latest release of Keras, that [longer offers support](https://github.com/keras-team/keras/releases/tag/2.4.0) for Keras backends other than Tensorflow, which renders the following code redundant

https://github.com/YaleDHLab/pix-plot/blob/cded92134070c235dd1ebe94e642e80cc4d380a1/pixplot/pixplot.py#L8

I'm managed to resolve this issue by installing `keras==2.3` - rather than 2.4 - prior to installing the pixplot library. 

I'd love it if this change were made to the repo itself. Thanks!

**Comment by duhaime** [comment]
This should be all set! 

If you notice any other strange issues with keras (or otherwise), please let us know!
