### ISSUE TITLE
metadata file format in readme vs code

### ISSUE THREAD

**Issue by ed-fish** [YaleDHLab/pix-plot#127]
I noticed that the metadata csv header needs to be lowercase, or the header needs parsing for both upper and lower. Perhaps update the example csv file in the readme or I am happy to send a pull request where the headers are always parsed to lowercase.

**Comment by duhaime** [comment]
@ed-fish Ah thanks for this! If you'd want to send a PR along, we'd be happy to merge it in!

**Comment by ed-fish** [comment]
Sure thing - will send over tomorrow.
