### ISSUE TITLE
Can't enlarge image from thumbnail / issue with image tags

### ISSUE THREAD

**Issue by basbuijse** [YaleDHLab/pix-plot#131]
Hi,

In the demonstrations in the README it is possible to click on an image to display its orginal size . However, when training pixplot with my own images, the only thing I can do is drag over the image or use lasso select (so can't seem to click on an image anymore to enlarge it). Is the enlarge feature removed or am I doing something wrong?

**Comment by duhaime** [comment]
Hello @basbuijse! If you are in the zoom/pan mode, you should be able to click on an image to see the full sized image. You might have to zoom a little closer to an image before attempting to click it...

If that's not working for any reason, I would verify that you're on the latest version (`pip install pixplot -U`) and try again.  Either way, if you follow up we're happy to assist!

**Comment by basbuijse** [comment]
@duhaime updating indeed worked for me, thanks! However, with this update the tags changed from "pipe delimited tags" to "(one) categorical label for the image". Am I still able to provide mutiple tags for one image? And if so, how?

**Comment by duhaime** [comment]
@basbuijse ah great! 

Yes, unfortunately we've moved to just a single categorical label for images. 

I think it could make sense to push a new release that re-adds "tags" alongside "category" in the metadata schema. Right now we're using "category" to control both the categorical layout and to highlight cells after users choose an option from the dropdown. Maybe it makes more sense to use "category" for the categorical layout and use "tags" to highlight / unhighlight images as users select options from the dropdown. Does that sound like a good way forward?

**Comment by basbuijse** [comment]
@duhaime Yea that would be great!

**Comment by duhaime** [comment]
@basbuijse If you `pip install pixplot==0.0.94` you can now pass pipe-delimited tags to highlight images with the dropdown. 

If you check that out and all is well, please feel free to close this issue. Either way, thanks for the follow-up!

**Comment by basbuijse** [comment]
@duhaine Thanks very much, I just tried it out and it works like a charm! However, imo it would also be nice to show the tags (below the image) when the image is enlarged. Right now, non of the tags are displayed. Would it be possible to implement this?

**Comment by basbuijse** [comment]
@duhaime Managed to fix this myself! Ill close this issue.
