### ISSUE TITLE
distutils error on Windows 10: .conda\envs\pixplot\lib\site-packages\pixplot\web': not a directory

### ISSUE THREAD

**Issue by AGrosserHH** [YaleDHLab/pix-plot#132]
Hi all,

I am trying to run pixplot on Windows and have installed it via Conda. Once I try to run pixplot I am getting the error message

Traceback (most recent call last):
  File "overall.py", line 45, in <module>
    pixplot_obj.pixplot_process()
  File "C:\Users\ga111873\Documents\GitHub\Image%20Analysis\ccode\1-ImageAnalysisPip_pre\ktpycluster\ktpycluster\Cluster_Pixplot.py", line 65, in pixplot_process
    pixplot.process_images(**self._config)
  File "C:\Users\ga111873\.conda\envs\pixplot\lib\site-packages\pixplot\pixplot.py", line 97, in process_images
    copy_web_assets(**kwargs)
  File "C:\Users\ga111873\.conda\envs\pixplot\lib\site-packages\pixplot\pixplot.py", line 110, in copy_web_assets
    copy_tree(src, dest)
  File "C:\Users\ga111873\.conda\envs\pixplot\lib\distutils\dir_util.py", line 124, in copy_tree
    "cannot copy tree '%s': not a directory" % src)
distutils.errors.DistutilsFileError: cannot copy tree 'C:\Users\ga111873\.conda\envs\pixplot\lib\site-packages\pixplot\web': not a directory

What do I make wrong? Any help would be much appreciated ..

Cheers,
Andi

**Comment by AGrosserHH** [comment]
HI, I needed to manually copy the web folder into the conda environment of Pixplot. Then it worked on Windows.

**Comment by duhaime** [comment]
@AGrosserHH sorry for your troubles! This is interesting. 

It could be a good idea for us to fix this to keep things simple for other Windows users. I'll reopen this until we unravel the mystery, but I'm glad to hear all is well for you!

**Comment by fr1ll** [comment]
I've run into the same issue and used the same workaround as @AGrosserHH.

I tried printing the [list of data files generated by setup.py](https://github.com/YaleDHLab/pix-plot/blob/576f3f9bdecb88ebdba0bca538492b583aca0a79/setup.py#L27) and it looked okay. I did some reading about setuptools and saw [some people comment](https://blog.ionelmc.ro/presentations/packaging/#slide:15) that it's best to use either `package_data` or a MANIFEST.in, but not both--but no one troubled to say _why_ this was best. I also read somewhere that yet another dependency, [setuptools_scm](https://github.com/pypa/setuptools_scm), can help with this kind of thing--but again, it wasn't clear to naive me why it is needed.

@duhaime if you have any ideas of ways I could try to narrow down this issue, let me know!

**Comment by duhaime** [comment]
Thanks for your help with this @fr1ll!

I've just tested this on a Windows 10 instance and the web directory is created properly, but if others encounter difficulties with this issue, please feel free to send a note along and we can reopen the issue.
