### ISSUE TITLE
Up the TensorFlow requirement to 2.2

### ISSUE THREAD

**Issue by stian-overasen** [YaleDHLab/pix-plot#135]
[TensorFlow 2.0.0](https://pypi.org/project/tensorflow/2.0.0/#files) which is set a a maximum dependency is not available for the latest Python (3.8). However, TensorFlow 2.2 is and PixPlot is working like a charm with that.

May I suggest you up the minimum version to 2.2.0 so PixPlot can be used with the latest Python?

https://github.com/YaleDHLab/pix-plot/blob/8b9946a4bfe2be8f7ce2b58066355fdfc1cf2c9e/setup.py#L39

**Comment by duhaime** [comment]
Ah, thanks for the heads up @stian-overasen ! This is great news. 

I believe `tensorflow>=1.14.0, !=2.0.*, != 2.1.*` is the best one can do in the setup.py to specify the version number. 

We'll want to run some tests to make sure the 2.2 version works across devices, but it's great to hear tensorflow now supports Python 3.8!

**Comment by pleonard212** [comment]
I have tested this combination  under Ubuntu 20 and a python **3.6** conda environment:

`conda install cudatoolkit=10.0`
`pip install tensorflow==1.14.0 tensorflow-gpu==1.14.0`

Newer versions of TF 1.x (1.15 etc) seem to trigger errors related to api deprecation.  

Not directly related to the issue of supporting TF 2.x but just thought I'd mention it as it may represent best mix for python 3.6

**Comment by duhaime** [comment]
@stian-overasen We're now looking into adding a pose extraction model that has a hard dependency on tensorflow 1.14.0, so for the nonce I think our best course of action is to suggest users create a conda environment 3.6 or 3.7 and then install tensorflow==1.14.0 in that environment, as @pleonard212 suggests. 

But it's good to know that tensorflow 2.2 is agreeable! Eventually we can move the pose extraction model to tensorflow 2.2, which will allow us to upgrade the version we use as well...
