### ISSUE TITLE
Filtering images

### ISSUE THREAD

**Issue by syldor** [YaleDHLab/pix-plot#14]
That's a great piece of code !

What would be an idea to dynamically filter images at runtime ? I could add some values in the plot_data.json file and then in the imageData object. But using buildGeometry and only draw some images doesn't seem to be the solution because the faces are already indexed.

Maybe using the z positioning to put the filtered images behind the scene ?

**Comment by duhaime** [comment]
@syldor Thanks for your note! I think there are a few ways you could show/hide images. One way to hide images would be to modify the `materialIndex` attribute of each `face` you want to hide -- just set the materialIndex of the given face to infinity and the faces will disappear.

For an example, you could go to the [demo](https://s3-us-west-2.amazonaws.com/lab-apps/pix-plot/index.html), open the dev tools in a recent browser, and run the following in the console:

```
// set all faces in the second mesh to a non-extant material idx (scene.children = [light, mesh, mesh])
scene.children[2].geometry.faces.map((f, i) => f.materialIndex = Number.POSITIVE_INFINITY);

// indicate that the groups in the affected mesh need updating
scene.children[2].geometry.groupsNeedUpdate = true;
```

To filter all but some particular images, you'd just need to do the book-keeping to know which index values should be skipped. How does that sound?

**Comment by syldor** [comment]
Thanks that's great. I have now the possibility to remove totally the image (```Number.POSITIVE_INFINITY```), but I also wanted to change the transparency. The transparency element is stored on the material and not the face so I have to duplicate the material with different transparency and change the ```materialIndex``` accordingly but it's not too complicated. I write that only for info :)

Also I have another question:
you chose to build your tool on the position of an image in an atlas, computed with `atlas_length`, `image_width` etc ...
Do you see a reason not too hardcode the image atlas position in the file `plot_data.json` ? I wanted to do that to be sure of the link between image and metadata but was wondering if there is an obstacle.
The `plot_data.json` would be like: 
`"positions": [[id, x, y, x_atlas32, y_atlas32, x_atlas64, y_atlas64, ...], ...]`

**Comment by duhaime** [comment]
@syldor That's a great question. I think it's actually best to have the size of each cell stored on a per-cell basis, as you've described. That increases the complexity of the book-keeping and data prep a decent amount, but it's an optimization I've wanted to make for some time.

When we return to this project in coming weeks I hope to tackle this. If you generalize this codebase to work with heterogenous input image sizes, we'd love a pull request!

**Comment by syldor** [comment]
Actually i didn't understand the difference between cell dimension and images dimensions, now i see it and that's a good way to do ! Thank you for your help.
