### ISSUE TITLE
Year slider not correctly styled in generated output

### ISSUE THREAD

**Issue by Pin0** [YaleDHLab/pix-plot#155]
Thanks for this great tool! Works like a charm!
However when providing a year column in the metadata.csv the generated slider does not show correctly in google chrome.

<img width="645" alt="Screenshot 2021-01-02 at 15 05 50" src="https://user-images.githubusercontent.com/3521008/103458824-0bed9d00-4d0c-11eb-9680-273abaf5a8ea.png">

For an example of my pixplot see: http://nijdam.nu/lego_pixplot/

**Comment by duhaime** [comment]
This is pretty cool data! Sorry about that slider--this should be fixed by https://github.com/YaleDHLab/pix-plot/pull/157

**Comment by duhaime** [comment]
@Pin0 just to follow up on this, you should be able to deploy these changes if you run the following lines:

```
# update to the latest pixplot
pip install https://github.com/yaledhlab/pix-plot/archive/master.zip

# update your web assets in ./output
pixplot --copy_web_only
```

Just run those lines in the same directory that has the plot above (if you run `ls` in that directory, you should see the `output` folder that contains your plot). 

Can I please ask you to let me know if this works for you? If you get stuck just let us know and we can assist!

**Comment by Pin0** [comment]
Just applied your change into the code and it works like a charm, Thanks!
