### ISSUE TITLE
Solution needed for metadata with lots of categories

### ISSUE THREAD

**Issue by Pin0** [YaleDHLab/pix-plot#156]
I have a lot of categories see screenshot:
<img width="341" alt="Screenshot 2021-01-02 at 15 07 50" src="https://user-images.githubusercontent.com/3521008/103459021-65ee6280-4d0c-11eb-93ed-3fe45c507515.png">

It would be nice if someone can invent some nice solution for this (maybe scroll the list, or some autocomplete search field etc.)\

See example here: http://nijdam.nu/lego_pixplot/

**Comment by pleonard212** [comment]
I would recommend doing some hand-curation of this list, using your own expert judgement about which categories make sense to combine.  You could use a tool such as OpenRefine to explore which ones are very small (only a few sets) and might logically group with others.  The natural length of this UI affordance can't be taller than the browser window on a normal-sized screen.

**Comment by Pin0** [comment]
I'll do that, great suggestion Thanks!
