### ISSUE TITLE
get_categorical_boxes fails if number of tags == 1

### ISSUE THREAD

**Issue by ed-fish** [YaleDHLab/pix-plot#163]
I noticed that if I have the same tag for all my data, `line: 889 get_categorical_boxes()` fails as the list index is out of range for `y_spots`

To fix I have to add a random tag to my data so that `box_len > 1`

While it might be normal to remove tags if they are uniform across the data, I debug over a small sub sample. 

Here is the output:

``` File "pixplot/pixplot.py", line 822, in get_categorical_layout
    boxes = get_categorical_boxes([i["count"] for i in keys_and_counts], margin=margin)
    File "pixplot/pixplot.py", line 889, in get_categorical_boxes
    y = y_spots[y_spot_index]
    IndexError: list index out of range
```
and a sample of the metadata csv:

```
filename,tags,description, Year
58XXRayIII.jpg,ScienceFiction,58XXRayIII,2000
1SaxRohmersSumuru.jpg,ScienceFiction,1SaxRohmersSumuru,2000
```

**Comment by duhaime** [comment]
Thanks for reaching out @ed-fish! 

I just pushed a commit (https://github.com/YaleDHLab/pix-plot/commit/25eca1f031a3a7254bf44d5b1b54ce3c2a689afc) that should resolve this issue. 

If you have a moment to try it out, could I please ask you to install the latest version and see if that sets all to right? I'd be grateful if you could!

**Comment by duhaime** [comment]
@ed-fish just circling back--if you have a second to try the latest code on master (`pip uninstall pixplot && pip install https://github.com/yaledhlab/pix-plot/archive/master.zip`) I'd be grateful if you could let us know how it goes!

**Comment by duhaime** [comment]
I'm going to close this out but please reopen it if necessary!
