### ISSUE TITLE
Recursion problem with umap?

### ISSUE THREAD

**Issue by tokee** [YaleDHLab/pix-plot#17]
While processing 26K images, pix-plot threw the exception
```
Traceback (most recent call last):
  File "pix-plot/utils/process_images.py", line 349, in <module>
    PixPlot(image_dir=sys.argv[1], output_dir='output')
  File "pix-plot/utils/process_images.py", line 58, in __init__
    self.write_json()
  File "pix-plot/utils/process_images.py", line 261, in write_json
    'positions': self.get_2d_image_positions(),
  File "pix-plot/utils/process_images.py", line 173, in get_2d_image_positions
    model = self.build_model(self.image_vectors)
  File "pix-plot/utils/process_images.py", line 198, in build_model
    return model.fit_transform( np.array(image_vectors) )
  File "/usr/local/lib/python2.7/dist-packages/umap/umap_.py", line 1402, in fit_transform
    self.fit(X)
  File "/usr/local/lib/python2.7/dist-packages/umap/umap_.py", line 1361, in fit
    self.verbose
  File "/usr/local/lib/python2.7/dist-packages/umap/umap_.py", line 391, in rptree_leaf_array
    except (RuntimeError, RecursionError):
NameError: global name 'RecursionError' is not defined
```
Note: The line numbers for pix-plot are a bit off because I inserted a few lines, as described below.

This was with Python 2.7.12. It worked fine with a sample corpus of 70 images. The machine had 7GB of free mem when I started processing. I tried adding a line with `sys.setrecursionlimit(2000)` at the start of the script (Random Page On The Internet said that the default for Python is 1000), but that did not change anything.

What is the highest number of images that pix-plot can handle?

**Comment by duhaime** [comment]
@tokee this looks like a UMAP error alas, possibly https://github.com/lmcinnes/umap/issues/23. We've certainly pushed 30k images through the pipeline before.

We've mostly used 3.5 for data processing, but have tested 30k on 2.7 as well and it came through just fine. That said, UMAP learn 0.1.5 (the version of umap-learn specified in `utils/requirements.txt`) does throw intermittent errors, some of which may have been patched since 0.1.5. You could try:

```
pip install umap-learn -U
```
You could also raise a thread in https://github.com/lmcinnes/umap to see if @lmcinnes has a hunch? 

Either way I'll see if I can replicate on my end (I'm waiting for a quad-core to process 30k images now as it happens).

**Comment by lmcinnes** [comment]
I believe this is a data dependent issue -- UMAP uses random projection trees to work toward finding nearest neighbors efficiently. The goal here is to build a tree where each node splits the data by a random hyperplane, and the children are the data points on either side of the hyperplane. This is built recursively until the leaves contain only at most some number of points.  Somehow this is hitting the recursion limit. By construction the hyperplane will split off at least one point (and should on average roughly split the data in two). This means that in the "perfect" case of constant splitting it should hit the recursion limit at 2^1000 points (which should be more than enough for most people). In the worst case it could theoretically fail at 1000 points, but that means managing a worst case split *every single time*. That seems unlikely unless there is something unfortunate/weird about the data distribution. I don't have any datasets that I can reproduce this with, so I've never managed to track it down.

I know that doesn't solve the problem, but it may provide some pointers on what to look at in your data as to what may be causing the issue. One approach may be to try using cosine distance instead; that will use angular RP-trees which might avoid the problem.

**Comment by duhaime** [comment]
One other thought: could setting a different `random_state` parameter (a random seed) when initializing UMAP help in this case? I can imagine that if one's dataset split into a number of branches close to the system's max recursion limit in one run, a different `random_state` could potentially keep one from hitting that limit in the next...

Syntax: `UMAP(n_neighbors=5, min_dist=0.01, random_state=42).fit_transform(data)`

**Comment by tokee** [comment]
Thanks for the writeup, @lmcinnes. My data are photos from the last 15 years, most of them from the family album. They are all in color and most of them has one or more persons, but besides that they vary quite a bit. They are a selected subset, so they should be without duplicates and there are very few nearly-similar images.

I have updated `umap-learn` and have re-started the process. If that fails I will try with a recursion limit of 30K. If that fails I will try with Python 3. I'll post my findings here.

**Comment by tokee** [comment]
With the updated `umap-learn` it took 2 hours before it threw an exception. That's up from 15 minutes, so I am hopeful.
```
Traceback (most recent call last):
  File "pix-plot/utils/process_images.py", line 349, in <module>
    PixPlot(image_dir=sys.argv[1], output_dir='output')
  File "pix-plot/utils/process_images.py", line 57, in __init__
    self.load_image_vectors()
  File "pix-plot/utils/process_images.py", line 184, in load_image_vectors
    print(' * loaded', c+1, 'of', len(self.vector_files), 'image vectors')
IOError: [Errno 9] Bad file descriptor
```
I did a diff between the generated `.npy`-files and the source images and found that 251 images out of the 26K that did not have a corresponding `.npy`-file. I looked at the first 20 of the no-npy-generated images and they seem to be fine, so that's a bit of a mystery. I have moved them to another folder for future examination and have restarted the process with the remaining images.

**Comment by duhaime** [comment]
Thanks very much for your help @lmcinnes!

**Comment by tokee** [comment]
Success! With the updated version of `umap-learn` all remaining problems were either due to invalid images or tricky filenames. And it turns out that the final mapping after all the `.npy`-files has been generated in less than an hour so I am hopeful for further scaling up.

The end result is great. There is no doubt that images with spatial locality are also thematically similar. I put it on http://ekot.dk/dagbog/cluster/ if you want to have a look. It's behind ADSL, so you'll have to wait half an eternity for the large thumbnails to load.

This was just an experiment, but I learned a lot and it showed that pix-plot works well for a collection with diverse photos. Putting on my Day Job Hat, I'll look into how we can apply this to our image collections. Thank you for your help.

**Comment by tokee** [comment]
I guess  a newer version of `umap-learn` would be needed for general closure? Or is it only me that has encountered problems with the old one?

**Comment by lmcinnes** [comment]
Glad this got resolved! Thanks @duhaime and @tokee !

**Comment by duhaime** [comment]
@tokee We haven't heard of others, but I'll update it to be safe...
