### ISSUE TITLE
Customizing color of lasso-selected images? Non convex lasso selection?

### ISSUE THREAD

**Issue by vdet** [YaleDHLab/pix-plot#175]
Hello,

First of all thanks for the excellent and super useful software!

I am adapting it to my application and wish to change the color of image border upon lasso selection (currently yellow), because it is barely visible with my images. I am no web expert... Tweaking `output/assets/css/style.css` and  `output/assets/js/tsne.js` led me nowhere. Is there any way to turn cell borders green upon selection and possibly make it thicker?

In addition, the shape I am trying to select (umap and geographic views) are typically *not* convex. It there any way to disable the convexity constrain?

Best,

Vincent

**Comment by duhaime** [comment]
Thanks for reaching out @vdet! 

Curiously enough, those border colors are specified in the [`borderColor` uniform](https://github.com/YaleDHLab/pix-plot/blob/master/pixplot/web/assets/js/tsne.js#L1233) passed to the shaders:

```
  value: new Float32Array([234/255, 183/255, 85/255]),
```

To change the border color, we just need to change the array value, which represents the reg, green, and blue values for the border. Those values have to be scaled 0:1, so if you had rgb values you could divide by 255 and write the results into the Float32Array constructor (just as the code above does!). 

To make the border wider, you can provide a bigger float value to the [`borderWidth`](https://github.com/YaleDHLab/pix-plot/blob/master/pixplot/web/assets/js/tsne.js#L1229) uniform. 

Relaxing the convexity constraint is interesting. In theory, you could change [the value returned by `Lasso.prototype.getHull`] from `return hull` to `return this.points`. The resulting behavior hasn't really been explored much, so you may get strange results if you draw lines that intersect. But that should let you draw more complex polygons!

<img width="481" alt="Screen Shot 2021-04-22 at 4 09 44 PM" src="https://user-images.githubusercontent.com/4801116/115778848-3d56ab00-a385-11eb-91e0-d7b0b938e763.png">

If you try any of this out we'd be glad to hear how it goes!

**Comment by vdet** [comment]
Thanks a lot, the fixes worked perfectly. Indeed the selection becomes confusing when the lasso line crosses itself. But this is still a better option for me.

Vincent

**Comment by duhaime** [comment]
Perfect! I'll close this out, but please feel free to reopen if necessary
