### ISSUE TITLE
Allowing pre-computed user latent space, UMAP and clustering

### ISSUE THREAD

**Issue by vdet** [YaleDHLab/pix-plot#180]
Hello,

In my situation imageNet is irrelevant and I also use my UMAPs outside of pix-plot. Thus, I tweaked the code to read two variables `umap_x` and `umap_y` from the metadata file, bypassing the tensorflow and umap code in pix-plot.

The same applies to HSDSCAN, which again I use for all sorts of purposes and don't want to recompute. I also need to tbe run with options not addressed in pix-plot. I have not fixed that yet, but the presence of a column `hdbscan_clusters` in the metadata could disable the HDSCAN calculation in pix-plot.

I guess all this could be easily be default behavior, greatly expanding the application range of pix-plot. First look for vars in metadata, compute them if they are not around. User latent space could be specified with a `--latent` flag.

On/off flags for specific mappings could be useful. For example the A-Z mapping is relevant only to applications for which file names mean something. 

Cheers,

Vincent

**Comment by duhaime** [comment]
Thanks for these good thoughts @vdet. We have considered the idea of allowing users to specify custom x, y, (and optionally z) coordinates for input images to designate their own latent space. Allowing one to specify umap_x, umap_y (and optionally umap_z) for the same would be great too, as would ingesting cluster identifiers. 

Like the switch between textured sprites / single color points, these changes would take a little more doing and will take a little longer for us to implement. If you would have any interest in trying your hand at a pull request for some of these user-specified data fields, that would be awesome!
