### ISSUE TITLE
QH6214 qhull input error: not enough points(2) to construct initial simplex (need 3)

### ISSUE THREAD

**Issue by vdet** [YaleDHLab/pix-plot#182]
Hi Douglas,

One of my data set produced the error below. It's probaly caused by HDBSCAN not returning clusters, as it goes away if I enter my own cluster labels via the metadata file.

```
Traceback (most recent call last):
  File "/Users/detours/ai/ciga-resnet18/code/python/pix-plot-master/pixplot/pixplot.py", line 1383, in <module>
    parse()
  File "/Users/detours/ai/ciga-resnet18/code/python/pix-plot-master/pixplot/pixplot.py", line 1380, in parse
    process_images(**config)
  File "/Users/detours/ai/ciga-resnet18/code/python/pix-plot-master/pixplot/pixplot.py", line 134, in process_images
    get_manifest(**kwargs)
  File "/Users/detours/ai/ciga-resnet18/code/python/pix-plot-master/pixplot/pixplot.py", line 424, in get_manifest
    'default_hotspots': get_hotspots(vecs=read_json(layouts['umap']['layout'], **kwargs), **kwargs),
  File "/Users/detours/ai/ciga-resnet18/code/python/pix-plot-master/pixplot/pixplot.py", line 1206, in get_hotspots
    hull = ConvexHull(positions)
  File "qhull.pyx", line 2433, in scipy.spatial.qhull.ConvexHull.__init__
  File "qhull.pyx", line 356, in scipy.spatial.qhull._Qhull.__init__
scipy.spatial.qhull.QhullError: QH6214 qhull input error: not enough points(2) to construct initial simplex (need 3)

While executing:  | qhull i Qt
Options selected for Qhull 2019.1.r 2019/06/21:
  run-id 771789821  incidence  Qtriangulate  _pre-merge  _zero-centrum
  _maxoutside  0
```

Best,

Vincent

**Comment by duhaime** [comment]
Thanks for this follow up @vdet! It seems your data defies convex hulls! 

I just pushed a commit that removes the hulls entirely, as they're no longer used. I also added a little borderWidth slider that lets one interactively set the border width for cluster membership / lasso membership highlights:

![output](https://user-images.githubusercontent.com/4801116/115902066-0093be00-a430-11eb-80fd-0a5967957ac6.gif)

Hopefully that makes it a little easier to identify lasso'd cells or hotspot members from afar with larger datasets!

Also, your comment about the -1 clusters from HDBScan reminded me that we weren't throwing that cluster away previously! So there was one bunk cluster that was being included; now it's removed :)

**Comment by vdet** [comment]
Hi Douglas,

pixplot.py ran without a glitch, but unfortunately, data fail to load with the new commit. The http server said:
```
::1 - - [26/Apr/2021 15:00:27] "GET /output/ HTTP/1.1" 200 -
::1 - - [26/Apr/2021 15:00:27] "GET /output/assets/css/style.css HTTP/1.1" 304 -
::1 - - [26/Apr/2021 15:00:27] "GET /output/assets/js/tsne.js HTTP/1.1" 200 -
::1 - - [26/Apr/2021 15:00:27] "GET /output/assets/vendor/dist/d3.min.js HTTP/1.1" 304 -
::1 - - [26/Apr/2021 15:00:27] "GET /output/data/manifest.json HTTP/1.1" 200 -
::1 - - [26/Apr/2021 15:00:27] "GET /output/data/imagelists/imagelist-387a989c-a68e-11eb-a74a-38c9861de4fc.json HTTP/1.1" 200 -
::1 - - [26/Apr/2021 15:00:27] code 404, message File not found
::1 - - [26/Apr/2021 15:00:27] "GET /favicon.ico HTTP/1.1" 404 -
```
file `favicon.ico` is in `output/favicon.ico`, not in `./favicon.ico`. So somehow the wrong path is provided to the server.

Vincent

**Comment by duhaime** [comment]
@vdet Curious! Is there any chance your browser has cached the path to the old imagelist? If you were to reset your browser cache and try to load the plot again, does the 404 disappear?

Another way to test the caching hypothesis is to look inside `./output/data/manifest.json` and look at the path to the `imagelist` etc. listed there. Those should be the paths that your browser is requesting. If they're not, then you might need to clear your cache (or in Chrome, open the dev tools, select the Network tab, and check the box that says "Disable cache"). 

I'm happy to follow up if you try these steps and send feedback!

**Comment by vdet** [comment]
That was the problem! Sorry. The functionality you implemented worked fine. Thanks!
Vincent

**Comment by duhaime** [comment]
Ah excellent! As they say, there are only two hard things in computer science: 

1. cache invalidation
2. naming things
3. and off by one problems
