### ISSUE TITLE
Loading user hotspots

### ISSUE THREAD

**Issue by vdet** [YaleDHLab/pix-plot#187]
Hi Douglas,

Beside writing them in place of `data/hotspots/hotspot-{ID}.json`, is there another way to load user-saved hotspot?

Vincent

**Comment by duhaime** [comment]
@vdet Good question! I think this is still undocumented (we're planning a documentation sweep soon), but if you click the little icon that says "Save Hotspots", you should get a file named `user-hotspots.json`. If you place _that_ file into `./data/hotspots` you should be good to go. 

This seemed the simplest way to approach this kind of data persistence without requiring a server, but if you have other thoughts for better user experience, we certainly welcome them!
