### ISSUE TITLE
LOD config bug

### ISSUE THREAD

**Issue by kruus** [YaleDHLab/pix-plot#191]
The following gave me wrong behavior:
https://github.com/YaleDHLab/pix-plot/blob/0a868442980f42b93d9ec8bf5893299d36fe288f/pixplot/web/assets/js/tsne.js#L53-L55
- The setting for `texture` seems safe.
- `lodTexture` gave me a bug on my laptop
  - For me, 2**13 was too large, leading to a console message that the texture had been down-sized to `webgl.limits.textureSize` (8192-->4096).  This led to **_wrong_** displayed images and console errors about **_coordinates out of range_** when zooming in.
- `atlas` might be unsafe for other people

One way to make things work is **`lodTexture : Math.min(2**13,webgl.limits.textureSize),`**.

Perhaps be similarly paranoid about the `atlas` default.

Erik

**Comment by duhaime** [comment]
Thank you for your note @kruus! Entirely agreed! Would you want to submit a pull request to introduce that change?

The atlas size is actually just the size of incoming atlas images. Those atlases are taken apart and recombined into textures, where each texture can contain one or more atlas images. So we can probably leave the atlas at 2048 and allow the transformation of atlases to textures to take care of the atlases.

If you can send on a pull request with the `lodTexture` change, that would be fantastic! Else we can certainly get this changed...

**Comment by kruus** [comment]
Will do, tomorrow.

**Comment by kruus** [comment]
Thanks!

**Comment by duhaime** [comment]
Thanks for your pull request @kruus! :)
