### ISSUE TITLE
Lasso and Picker should cooperate

### ISSUE THREAD

**Issue by kruus** [YaleDHLab/pix-plot#200]
1. deselections in *View Selected* currently change `this.selected`.  This means clicking images following *n* deselected images are *out-by-n* and display the wrong image.  Ex. If you deselect the first image, all remaining ones are out-by-one when asking for the detailed view.
2. deselections (and new number selected) should get reflected in main display on closing *View Selected* window
    - currently if you create a new cluster, you get the correct-but-not-as-displayed version.
3. lasso and picker (Shift + Click) should cooperate (i.e. lasso and shift-click can toggle individual images to the selected ones)
   - I ended up using Ctrl-drag for lasso, iirc, because it was easy for me to make mistakes between Shift-Click and Shift-Drag and *lose* some possibly detailed work.

Anyway, code was clear enough that I've a decent "good enough for now" version addressing above.

**Comment by duhaime** [comment]
Thanks very much for this writeup @kruus! We should be able to clean some of this up next week... 

Please keep the issues rolling if you spot other unexpected behavior!

**Comment by kruus** [comment]
- Thanks, for ideas, feel free to look at my [close-modal-window](https://github.com/kruus/pix-plot/blob/e277a0548e71121ceb346703e5535853b85ed617/pixplot/web/assets/js/tsne.js#L1849-L1878)
- modal selected count [without touching `this.selected`](https://github.com/kruus/pix-plot/blob/e277a0548e71121ceb346703e5535853b85ed617/pixplot/web/assets/js/tsne.js#L1918-L1930)
- and [`lasso.draw` reusability split](https://github.com/kruus/pix-plot/blob/e277a0548e71121ceb346703e5535853b85ed617/pixplot/web/assets/js/tsne.js#L2009-L2035)

Maybe you can come up with something cleaner/faster.

Other issue: Does your hotspot scrollbar work? Mine was not appearing.  Fixing mostly involved adjusting `styles.css` width issues and one ugliness for scrollbar height.  Mine works now, but my adjustments were super-ugly -- I really just poked at it until it worked.

Excellent timing -- I'm taking vacation next week, while you work on this!

**Comment by pleonard212** [comment]
Hi Kruus! Quick question on the scrolling -- sounds like you both don't have a visual scrollbar, and that mousewheel/trackpad drag is not moving the list of hotspots up and down correctly?
