### ISSUE TITLE
Dependency issue with Numba 0.54

### ISSUE THREAD

**Issue by mannu-arneja** [YaleDHLab/pix-plot#232]
This error occurs when generating pixplot:
`ImportError: numpy.core.multiarray failed to import`

Issue with new release noted here: [https://github.com/numba/numba/issues/7339](url)

A solution until that is sorted is to specify previous version in setup.py
`'numba==0.53'`

**Comment by duhaime** [comment]
Thanks @mannu-arneja ! If you'd like to send a pull request to change that line we'll be happy to merge it!

**Comment by mannu-arneja** [comment]
Thanks @duhaime for this great project!
