### ISSUE TITLE
Location lookup from image

### ISSUE THREAD

**Issue by tokee** [YaleDHLab/pix-plot#28]
When an image is clicked, the URL changes to `http://example.com/pixplot/#imagename`. Judging from how the cluster-links works, it seems doable to make it work the other way around, so that changing the URL would make the view jump to the corresponding image.

This feature would allow for bookmarking and act as a building block for an image searcher by making it easy to see the found image in context.

**Comment by duhaime** [comment]
@tokee This is a great idea, thanks for sending it. I just pushed `fly-on-hash-change` to implement this behavior. If you have a second could you please give that a try and let me know if it fits the bill? If so I'll merge it and close this issue out; if not I'm happy to iterate...

**Comment by pleonard212** [comment]
This seems to work; some side effects are:

1) Safari on Mac goes into a pseudo-loading state (partial blue loading bar.) Chrome does not.
2) Not a new issue, but clicking on left-hand cluster does not change URL
3) Do we need to persist this URL-based zooming after loading screen?  Think currently the hash doesn't zoom you if you haven't loaded the website yet.

**Comment by duhaime** [comment]
Ah, yes, we probably should check for a hash on page load and fly to the requested image (per #3). Adding the hash to the url to satisfy #2 should be straightforward. #1 is curious. I'm going to hunt around a bit for more information on why the progress bar is displayed...

**Comment by tokee** [comment]
@duhaime Thanks for implementing on this! It works fine (firefox/Ubuntu) for changing the URL when the page is loaded. But as you note above it has no affect on first visit, so bookmarking is not possible.
