### ISSUE TITLE
Create deeplinking mechanism

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/pix-plot#30]
so users can deeplink each image to another host with the same image

**Comment by pleonard212** [comment]
Possible ways to do this include:

1. Having each image's filename express it's primary key; python scripts then concatenate that variable with a longer URL.
2. Have an external .csv or .json file that contains a filename key and a url column. Complicates ingest story a bit?  We lose the elegance of "just process this directory full of images."

**Comment by duhaime** [comment]
this is present in the `experimental` branch!

**Comment by duhaime** [comment]
done!
