### ISSUE TITLE
Idea: split up positions and clusters into 2 json files

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/pix-plot#33]
Curating the k-means generated clusters is unwieldy due to the size of the positions data in the json file.  Generating a separate `clusters_data.json` (perhaps even pretty-printed, because _n_ is only 20 by default) would make editing this file easier.

**Comment by duhaime** [comment]
Ah, that's a good idea! It shouldn't be hard at all to implement, once this geometry optimization refactor is done...

**Comment by duhaime** [comment]
This feature is also present in `experimental`

**Comment by duhaime** [comment]
done!
