### ISSUE TITLE
Add feature to print time taken at each step

### ISSUE THREAD

**Issue by sandeeprepakula** [YaleDHLab/pix-plot#40]
Request to enhance the code for printing time taken for each of the steps like building thumbs, making 2D projections, computing clusters, etc. 

Building 2D projections is taking for ever in my case with 300 clusters and 80K images. Any reason why?

**Comment by duhaime** [comment]
@sandeeprepakula Do you just want to know the cumulative time consumed during each step of processing? Would it be sufficient to add timestamps in each of the log statements displayed on the console?

Can you say more about your system hardware? How many cores are you running on, and how much RAM do you have? KMeans (the clustering approach we use) is one of the [fastest](http://hdbscan.readthedocs.io/en/latest/performance_and_scalability.html) clustering techniques, but if you are out of RAM and are swapping, that will slow things down very quickly.

Do you have access to a machine with beefier hardware, such as a university research cluster or a sizeable AWS instance? If so, the easiest solution might be to leverage one of those hardware setups...

**Comment by sandeeprepakula** [comment]
Yes, I do use AWS for my requirement. Just printing the timestamp would also help into the logs or to the terminal as an stdout.

**Comment by saketkc** [comment]
This is partially addressed by #59

**Comment by duhaime** [comment]
We're now printing timestamps at the start of each step, which should take care of this. If you'd like to revisit this idea, please reopen this issue!
