### ISSUE TITLE
Support for timeline in Pix plot 

### ISSUE THREAD

**Issue by sandeeprepakula** [YaleDHLab/pix-plot#42]
Is it possible to have timeline feature visualisation after selecting a cluster?

**Comment by pleonard212** [comment]
It's possible that time could be the "z-axis" in a future version of the tool -- right now, Z is just jitter to avoid too many overlapping photos at one point. 

We're working on some improvements for explicit metadata, and date is definitely one of the things we have our eyes on.

**Comment by duhaime** [comment]
@sandeeprepakula I'm intrigued by this idea -- do you have a little sketch of the kind of timeline you are imagining?

Not all data that will be processed by this code will have time/date stamps, but for those datasets that do this could be an interesting feature.

I'd love to see what you're imagining...

**Comment by sandeeprepakula** [comment]
Thanks for considering this idea. 

I have some idea like if I select one of the generated clusters, it should show me only the images from the selected cluster with timeline (given as metadata) after filtering images from every other cluster.

**Comment by dmreagan** [comment]
@sandeeprepakula For a timeline view, you might take a look at [VIKUS Viewer](https://vikusviewer.fh-potsdam.de/).

**Comment by duhaime** [comment]
Well two years later we've sketched out support for a date-based layout. For future readers, feel free to consult https://github.com/YaleDHLab/pix-plot/pull/110

This is still pretty experimental, so if you give this a try and see anything you think should be changed, please feel free to follow up!
