### ISSUE TITLE
pix-plot: unknown command line flag

### ISSUE THREAD

**Issue by redgoatdog** [YaleDHLab/pix-plot#43]
I am trying to make my own pix-plot however when I try to run this line;

`python utils\process_images.py "C:\Users\oakie\Pictures\*.jpg"`

It errors and I get this as the output;

Traceback (most recent call last):
  File "utils\process_images.py", line 22, in <module>
    FLAGS.model_dir = '/tmp/imagenet'
  File "C:\Users\oakie\AppData\Local\conda\conda\envs\2018Summer\lib\site-packages\tensorflow\python\platform\flags.py", line 88, in __setattr__
    return self.__dict__['__wrapped'].__setattr__(name, value)
  File "C:\Users\oakie\AppData\Local\conda\conda\envs\2018Summer\lib\site-packages\absl\flags\_flagvalues.py", line 496, in __setattr__
    return self._set_unknown_flag(name, value)
  File "C:\Users\oakie\AppData\Local\conda\conda\envs\2018Summer\lib\site-packages\absl\flags\_flagvalues.py", line 374, in _set_unknown_flag
    raise _exceptions.UnrecognizedFlagError(name, value)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'model_dir'

Do you know what is going on, any suggestions. I am using Windows OS and Anaconda prompt. I have everything I need installed and everything seems to be working expect when I try to actually run pix-plot

**Comment by pleonard212** [comment]
Do you happen to know the version of tensorflow you're using? I have a branch that throws in a little change to make things compatible with 1.5 and up:

https://github.com/YaleDHLab/pix-plot/commit/9fda8295d0e398ee34c400798639baeb744cc775

**Comment by duhaime** [comment]
@redgoatdog As @pleonard212 mentioned, this problem will occur if your version of tensorflow is more recent than `1.2.0` (the version used by the current codebase).

A simple fix would be:

```
pip uninstall tensorflow
pip install tensorflow==1.2.0
```

If you run that then rerun `python utils/process_images.py data/*.jpg` are you able to process your data?

**Comment by redgoatdog** [comment]
Yes the tensor flow version was the problem, thank you both.

**Comment by duhaime** [comment]
@redgoatdog Is it alright to close this issue in that case?
