### ISSUE TITLE
Names of the images/data

### ISSUE THREAD

**Issue by redgoatdog** [YaleDHLab/pix-plot#48]
Do the Images need to be named a certain way or put in a certain way?
For example, can the image names have spaces in then, or can they be numbers. Also, can you use other images besides jpg.

**Comment by pleonard212** [comment]
In theory, the tool could work with a variety of formats.  If you find specific problems with common ones (TIF, GIF, PNG) let us know. 

A common problem is when dealing with a historical archive that's been digitized in pure greyscale. These images need to be put into the sRGB color space before they can be processed by TensorFlow.

The current version of the code should handle most filenames, but spaces in directories or files can cause a variety of problems and should probably be replaced by underscores.  Images named with numbers only will be just fine.

**Comment by duhaime** [comment]
@redgoatdog Did Peter's follow-up raise any questions, or is it safe to close this issue out?
