### ISSUE TITLE
Is there a way to see all images from all angles?

### ISSUE THREAD

**Issue by redgoatdog** [YaleDHLab/pix-plot#57]
Is there a way to change the code so that you can rotate the camera 360 degrees and still see all the images. Right now if you rotate it 180 degrees, all the images disappear.

**Comment by duhaime** [comment]
@redgoatdog right now this is not possible. We're rewriting the display logic to use textured point sprites as the geometric primitive, which will allow one to rotate completely around the scene, and which will ensure the images are always orthogonal to the view plane, so check back in a bit!
