### ISSUE TITLE
Question: absolute limit of images that can be plotted?

### ISSUE THREAD

**Issue by vinaysp** [YaleDHLab/pix-plot#58]
Hi all,

Just a quick question, wanted to ask what the maximum number of images that can be plotted on pix-plot. I know the examples show around 27,000 images being plotted but what would be the absolute maximum? I have a dataset consisting around 240,000 images that are 64x64pixels and was wondering if it would be at all possible to plot maybe half this dataset.

Thanks.

**Comment by duhaime** [comment]
Thanks for reaching out @vinaysp. In short, the viewer can handle your full data set, but performance (measured by frames per second) won't be great at the moment unless you have a beefy graphics card. We're working on a complete shader rewrite that will help this quite a bit, so stay tuned.

For now, I'd try an initial pass that samples maybe 20% of the data, and if performance is decent on your hardware I'd increase the number (you can skip reprocessing of already processed images if you change the booleans in the PixPlot constructor in `utils/process_images.py`).

**Comment by vinaysp** [comment]
@duhaime ok great thanks for the info, will work with 20% and go from there. I will also close this issue, just wanted to ask about current capabilities of the viewer.
