### ISSUE TITLE
Making selective images hidden or invisible 

### ISSUE THREAD

**Issue by redgoatdog** [YaleDHLab/pix-plot#60]
I was wondering if you have any advice or if there is anyway to allow images to be visible and invisible in pix-plot. I have set up my images with dates as their names, and what I want to do this after a button is clicked I want to make ever year, expect the year the button represents, invisible. I have been working on this for awhile but I have yet to find a solution.   Any help would be very much appreciated.

**Comment by duhaime** [comment]
@redgoatdog Thanks for your note. This idea came up in one previous thread that you may find interesting: https://github.com/YaleDHLab/pix-plot/issues/14 In general, there are a few ways to do this, but setting the materialIndex property of the faces you want to hide is a quick and dirty way.

We're working on a number of changes to the app that will allow transitions between layouts and filtering, but the heavy lifting right now is in optimizing the number of images that can be rendered with high FPS. In any event, that's to say we're working on this too.

If you give the approached linked in #14 a whirl and get stuck feel free to follow up and I'll be happy to try and help...

**Comment by duhaime** [comment]
@redgoatdog I wanted to check in to see if you're still having troubles, or if we can close this issue? I'd be grateful if you could follow up...

**Comment by duhaime** [comment]
this is also present in the `experimental` branch

**Comment by duhaime** [comment]
this is now on master!
