### ISSUE TITLE
Connect from a client computer

### ISSUE THREAD

**Issue by NTNguyen13** [YaleDHLab/pix-plot#61]
I install and run pix-plot on a computing server, but it doesn't support WebGL. How can I run it on the server (the computing part) and stream the result/viewer to the client computer I'm using? 
Thank you

**Comment by duhaime** [comment]
@NTNguyen13 The server that does the computing doesn't need to support WebGL. The browser agent that downloads the client-side files (HTML, CSS, and JavaScript) needs to support WebGL in order to parse the JavaScript correctly.

Does that make sense?

**Comment by duhaime** [comment]
@NTNguyen13 I wanted to check in to see if you're still having troubles, or if we can close this issue? I'd be grateful if you could follow up...

**Comment by duhaime** [comment]
I'm going to close this issue but please feel free to reach out if you have any additional troubles @NTNguyen13
