### ISSUE TITLE
Count images in a cluster

### ISSUE THREAD

**Issue by Kesavadas** [YaleDHLab/pix-plot#65]
Question: Is it possible to get the number of images in each cluster?
Probably this is a dumb question since I have no background in image processing or machine learning.

**Comment by duhaime** [comment]
Thanks for your note @Kesavadas , that's a good question!

The easiest way to find the number of images in each cluster is to make the following changes to `utils/process_images.py`.

First, change line 16 to: `from collections import defaultdict, Counter`

Then, inside the function `get_centroids`, right after the line that says
`X = np.array(self.image_vectors)`
add the following:

```
# find the number of observations in each cluster
cluster_indices = model.fit_predict(X)
print(Counter(cluster_indices))
```

That will print out a counter object that maps each cluster index to the number of observations in that cluster. E.g. here's the output for a 20 cluster model with ~1000 images:

```
Counter({14: 261, 16: 247, 4: 211, 8: 200, 2: 190, 0: 160, 9: 144, 12: 133, 11: 90, 6: 79, 7: 76, 15: 68, 13: 65, 18: 64, 17: 59, 3: 56, 10: 46, 19: 32, 1: 30, 5: 19})
```

That output says that cluster index 14 has 261 observations, cluster index 16 has 247 observations, and so forth.

If any of this is unclear or if you have trouble making those changes, please feel free to follow up!

**Comment by duhaime** [comment]
@Kesavadas is it alright to close this issue? If so I'd be grateful if you could!

**Comment by Kesavadas** [comment]
Sorry for the delay ... I couldn't test it yet 
I will close it now 
If I encounter any issues I will get back to you
Thanks for your help

**Comment by duhaime** [comment]
No worries @Kesavadas, thanks for following up!
