### ISSUE TITLE
Gradual image enhancement

### ISSUE THREAD

**Issue by tokee** [YaleDHLab/pix-plot#67]
I tried generating a pix-plot with 270,000 images. I was able to view it (choppily) for 20 seconds in Chrome or 60 seconds in Firefox before it crashed the graphics system on my Ubuntu desktop with 16GB of RAM and integrated graphics on an i5 CPU. A colleague with a MacBook got nowhere with Safari (it complained about too much memory being requested) but was able to view it choppily with Firefox, which allocated 14GB of RAM. The 270K images are from our open image collection and we would very much like to use PixPlot on it in a way that is  usable for random visitors.

Glancing at the Google demo, the solution seems to be selective loading of higher-res images based on image proximity. This would also have the positive secondary effect that smaller collections would display nicely when zooming in.

Alas, JavaScript and Web-GL is very far from my knowledge bubble, so I don't know how to even approach this solution.

**Comment by tokee** [comment]
I ran some experiments with sprites and got pix-plot to display the 270K images using "only" 1½GB of RAM, but performance was horrendously bad. https://github.com/tokee/pix-plot/tree/sprites holds the code for those interested, but it is very much random hacking without any clean up at this point.

With what I've learned so far, it might be possible to either do some distance trick and use `Points` for the far-away images. Another idea would be to get the shader to take care of the texture part, as displaying hundred of thousands of same-texture sprites is in itself not too taxing: The problems is that they must have different textures. Really just thinking out loud here...

**Comment by tokee** [comment]
Your recording of 1M images looks great! I am happy to see that progress towards a more performant visualization is so far along. I'll throw away those pesky sprites and check out your branch instead.

I am a bit surprised about the non-overlapping idea. To me one of the great things about pix-plot is the "live" 3D view, where the change in viewpoint also means a visual change of the displayed structure, due to the stacking of images. If everything is made flat, it will be quite a different visualization.

Also, if everything is flat, wouldn't it make better sense to use a 2D-oriented viewer instead? A tile-based 2D viewer, such as OpenSeadragon, would mean virtually unlimited scaling from overview to full-res images.

**Comment by pleonard212** [comment]
One idea would be to allow both overlapping and non-overlapping arrangements, with the animation engine allowing folks to switch between them...

**Comment by duhaime** [comment]
Yes, I think it makes sense to have some layouts be more three-dimensional than others. My original idea for a layout with less overlap comes right from the [original Google Arts and Culture tsne viewer](https://experiments.withgoogle.com/t-sne-map) that @tokee mentioned above, where the images are projected into 2d then given y offsets using a heightmap (a cool technique!).

That kind of layout makes it easier to survey the images in a collection *and* boosts performance, so it's win win in my mind. I agree there are interesting possibilities with 3d layouts (I don't believe I've ever seen a 3d mosaic in webgl), so the plan is to support those too...

**Comment by tokee** [comment]
I have played around with the `experimental` branch and its current state far supersedes what I mentioned in this issue. The transition between layouts is very nice and rules out a "static" visualization such as OpenSeadragon, so please disregard that comment :smiley:  Consequently I am closing this issue. Thank you for your excellent work!
