### ISSUE TITLE
Flickering (and wrong) images when zooming in

### ISSUE THREAD

**Issue by sonovice** [YaleDHLab/pix-plot#68]
I just played on the experimental branch and as soon as I zoom in and the 32px thumbs are getting replaced with higher resolutions, the images start to flicker and often show only black rectangles or parts of the atlases:

![grafik](https://user-images.githubusercontent.com/8217108/55982839-10516700-5c9a-11e9-89fd-129a00662b2f.png)

I am not quite sure what is happening. While zooming, one can see that the correct data is loaded as well, but as soon as the zoom animation stops, things are as shown above.

Just wanted to report this bug in case you haven't already seen it. Amazing piece of work, though. Thank you so much!

(Though I don't think it's important: I used my own dataset and distance metric for it. Had no problems during the processing steps whatsoever.)

EDIT:
Chrome: Same problem
Microsoft Edge: Same problem
Firefox: Does not show the 32px thumbs at all. Also flickering and black rectangles, but no parts of the atlas files are shown.

**Comment by duhaime** [comment]
Hmm, that's really curious. This branch is definitely experimental but I haven't seen this behavior yet.

Is there any chance the output atlas files were somehow fed into the input script? One way to test if that's the case is to see if any of the images in `output/thumbs/128px` looks like a montage of images. (I've done that accidentally in the past by passing a wonky glob to the input script).

I can't see how the level of detail mechanism could create that kind of montage effect--it just fetches images from the `output/thumbs/128px` directory, adds them to a canvas texture, and then updates the attribute buffers for the appropriate images.

@sonovice if you have a second, can I ask your operating system and version? Any information you can send on your graphics card would be helpful too...

**Comment by duhaime** [comment]
@sonovice sorry I should have asked--could you also send your specific browser versions as well if you have a moment?

**Comment by sonovice** [comment]
I rebuild the entire data (over 47k images) to make sure I made no mistake and went over all files in the 128px folder but nothing suspicious came up.

Here are some specs of my system:
> OS: Windows 10 Pro Version 1803 (Build 17134.648)
> Gfx: NVIDIA GeForce GTX 1080 (8 GB), latest drivers
> 
> Chromium: v72.0.3626.96
> Firefox: v66.0.3
> Microsoft Edge: v17.17134

I made a quick screencast so you get a better picture of the issues: https://youtu.be/Z79qfBUZMys

And just in case I messed up my data, I uploaded everything here: http://www.web226.s186.goserver.host/t-sne/

**Comment by sonovice** [comment]
Just tried another computer: Things work as expected except Firefox only shows black rectangles instead of the 32px thumbnails but switches to 128px correctly. Oh and Chrome crashes constantly if I move around too much.

So I guess it has something to do with my gfx card. Not sure how (if at all) to solve that or even start debugging.

**Comment by tokee** [comment]
@sonovice Interesting enough, your sample page http://www.web226.s186.goserver.host/t-sne/ works fine on my system (Ubunty + Firefox), but when I try to render some of my own images with the latest `experimental` checkout, I get the black rectangles for the 32px thumbnails and non-flickering 128px versions upon zoom. Did you change anything since you uploaded the demo page?

**Comment by thomasegense** [comment]
demo url: http://www.web226.s186.goserver.host/t-sne/ 
does not work on my firefox, it freezes at 66% with this error on the console:

**XML Parsing Error: syntax error
Location: http://www.web226.s186.goserver.host/t-sne/output/centroids.json
Line Number 1, Column 1: centroids.json:1:1
TypeError: this.template is null[Learn More] tsne.js:1663:5
    init http://www.web226.s186.goserver.host/t-sne/assets/js/tsne.js:1663
    <anonymous> self-hosted:975
    onreadystatechange http://www.web226.s186.goserver.host/t-sne/assets/js/tsne.js:1736**

It works on both Chrome and Chromium. (Ubunutu)

**Comment by tokee** [comment]
Update: Uploading to an external server made my experiment work fine and reloading the version served from my workstation's local webserver also made it work. Now it displays fine everywhere, even when I reload. Maybe it's a timing issue?

**Comment by duhaime** [comment]
If you're using the SimpleHTTPServer (or http.server in Python 3) it could be a "server"-side caching issue. Try changing the port on which you're running to see if that's the case:

python -m http.server 7043 # python 3
python -m SimpleHTTPServer 7043 # python 2

Just change the integer value as a sanity check if you see strange behavior, especially if rebuilding the data...

**Comment by duhaime** [comment]
@sonovice I'm going to close this issue and create a new one on the FireFox problem, which I can replicate on Windows here. I think solving that will resolve this. If you see other strange behavior please feel free to open a new issue!

**Comment by pleonard212** [comment]
I've noticed a bit of flickering/texture mis-mapping too; I think it might be dependent on the video card's RAM in addition to the browser. Will try to do some testing to come up with some data...

**Comment by duhaime** [comment]
That'd be awesome if we could identify a dataset and device + browser that create this problem. There's definitely a flickering problem when images "[z-fight](https://en.wikipedia.org/wiki/Z-fighting)" -- two images at the same position will fight for control of the z plane which causes flickering. Jittering the images out a bit is meant to help that.

If you can find a dataset that causes this please let me know! I'll reopen this in the interim...

**Comment by pleonard212** [comment]
Here is an instance that triggers some flickering (Chrome, Win10, NVIDIDA P4000):

http://pixplot.yale.edu/v2/lund/

**Comment by pleonard212** [comment]
This took a while to figure out!  @duhaime discovered it was due to a difference in how NVIDIA and AMD GPUs treat casting between integers and floats.  I'll let Doug close this with the particular commit to the experimental branch that fixes it...

**Comment by duhaime** [comment]
The essential detail here was that NVIDIA and AMD evidently handle negative integer typecasting differently (at least in the context of fragment shaders). The change that fixes this behavior is https://github.com/YaleDHLab/pix-plot/commit/5dbcc5ba9e34eef9593eb292eaebc87e1f6433f5#diff-cdb833fcf0651bc90856afe53cba4c30R153

**Comment by duhaime** [comment]
I'll close this for now, but please feel free to reopen if you see strange behavior in the future @sonovice

**Comment by tfriedel** [comment]
I also experience this flickering. This is with a dataset of 17.000 images and a custom model trained on plant diseases.
My environment:
nvidia rtx 2070, windows 11. chrome and edge browser.
It looks like there's two images on top of each other ("z-fight"). However if I then use the lasso tool, there's only one image in this position.

[Demo](https://youtu.be/cUagZFrQzLw)
