### ISSUE TITLE
get the original image names and the centroid in a given cluster

### ISSUE THREAD

**Issue by dl002** [YaleDHLab/pix-plot#72]
This is a question I have. Can I get the names of the images that belong to all clusters?
For example, if my input images were named like img1.jpg, img2.jpg, and so on, can I get the cluster numbers and all images that belong to it and the centroid of that cluster. Like:
Cluster 1: img1.jpg, img4.jpg, ....................... : centroid: img4.jpg
Cluster 2: img6.jpg, img8.jpg, ....................... : centroid: img6.jpg
Cluster 3: img14.jpg, img41.jpg, ....................... : centroid: img41.jpg
Sorry if this is a very basic question, I am new to this area.

**Comment by duhaime** [comment]
Thanks for your question @dl002. You can certainly get this mapping with just a few small changes.

If you pop open the `process_images.py` utility, you'll see there's a function called `get_centroids()` in which the clustering happens. Inside that function, we fit a KMeans model then compute the centroids of each cluster. Right below [the line that computes those centroids](https://github.com/YaleDHLab/pix-plot/blob/master/utils/process_images.py#L276), you should be able to add something like:

    # pretty print the mapping from cluster id to images in cluster
    import pprint
    cluster_map = defaultdict(list)
    for idx, i in enumerate(fit_model.labels_):
      cluster_map[i].append(self.image_files[idx])
    pprint.pprint({'cluster_map': cluster_map})

That should display the mapping you describe above.

This works because [the KMeans model has an attribute `labels_`](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html) that contains the cluster id for each image in the dataset, in order. So we can iterate over those cluster ids and given the `ith` cluster id fetch the `ith` image and add that image. I'm happy to follow up if any of this is confusing...

**Comment by dl002** [comment]
@duhaime thank you very much for your code and the explanation. It is very helpful and it prints the cluster number and the members. In addition to the cluster members need the cluster centroid associated with each cluster too, so I tried the following:

    for idx, i in enumerate(fit_model.cluster_centers_):
      print(self.image_files[idx])`

My idea was to map the cluster number from the cluster members in your code. However, what this prints is different from what I see in the visualization. A different set of centroids appear in the visualization. I believe that when I click on the cluster number in the visualization, it shows the centroid's name in the URL, right? If that is the case, how I try to get the centroids is wrong. How do I get the centroids correctly?

**Comment by duhaime** [comment]
@dl002 oh sorry I didn't see you wanted the centroids in that object as well. A word on those centroids: We compute the raw centroids of each KMeans cluster, then we find the image that's closest to each centroid. That image will very rarely exist exactly where the centroid is, so there's naturally going to be a delta between the raw centroid and its nearest point/image in the space.

We can add the centroid values and the name of the image closest to each centroid with the following right after [the line that finds the index position of the image closest to each centroid](https://github.com/YaleDHLab/pix-plot/blob/master/utils/process_images.py#L278):

    # pretty print the mapping from cluster id to images in cluster
    import pprint
    cluster_map = defaultdict(lambda: defaultdict(list))
    for idx, i in enumerate(fit_model.labels_):
      cluster_map[i]['images'].append(self.image_files[idx])
    # add the centroids to the cluster map
    for idx, i in enumerate(centroids):
      cluster_map[idx]['centroid'] = i.tolist()
    # add the points to which centroids are assigned
    for idx, i in enumerate(closest):
      cluster_map[idx]['closest'] = self.image_files[i]
    # print the cluster map
    pprint.pprint({'cluster_map': cluster_map})

As you'll see, those centroids are defined in the 2048 dimensional space in which the image vectors exist before they're projected down into a lower dimensionality...

Looking at the code in your last note, it looks as if you were operating with the raw centroids (aka `fit_model.cluster_centers_`). To get the images that correspond to each cluster we just need to find the index of the image closest to each cluster (accomplished in the line 278 linked above in this note), then find the corresponding image within `self.image_files` as accomplished in the little snippet in this note.

I hope some of that helps a bit! If not I'm happy to follow up...

**Comment by dl002** [comment]
@duhaime Thank you very much. I works just as expected and thanks to your explanations I know what's happening inside. 

Your explanations are very clear :) . I suggest these to be added to the project wiki for people like me ;)

**Comment by duhaime** [comment]
Awesome, thanks for confirming @dl002. A wiki is a great idea. Much is changing in the next release of this codebase, and once that's all settled some wiki docs will be awesome. In any event, happy plotting!

**Comment by dl002** [comment]
That's great to know. Good luck with the next release and thank you again!

I am closing the issue as it is solved now.
