### ISSUE TITLE
ImageMagick Installation Issue

### ISSUE THREAD

**Issue by agl5000** [YaleDHLab/pix-plot#79]
When attempting to run the ImageMagick line of the Dependencies section of the ReadMe, the following error results:

`Error: No such keg: /usr/local/Cellar/imagemagick`

Is this an issue with version compatibility of Pix Plot and tensorflow?

**Comment by duhaime** [comment]
Ah, thanks for your note @agl5000. It seems you don't have imagemagick installed. Could you please try a simple `brew install imagemagick` and let me know how it goes?

**Comment by agl5000** [comment]
Thanks for such a quick reply--that worked, but when running the first instruction under "QuickStart", the python script, a new error is given:

`AttributeError: module 'tensorflow' has no attribute 'app'`

**Comment by duhaime** [comment]
I'm glad imagemagick is all set now!

The tensorflow error is likely due to the fact that tensorflow just released a major (non-backwards compatible) version 2.0. This codebase assumes users have the older 1.x tensorflow installed.

Would you be able to run a `pip install tensorflow==1.15.0` and then try to process your data again? (I'm submitting a pull request to prevent tensorflow 2.0 installations in the future...)

**Comment by duhaime** [comment]
@agl5000 any luck with tensorflow 1.x?

**Comment by agl5000** [comment]
It worked! Thanks for your help.

A couple roadblocks to pop on the way, but I got around them:
1) The script returned many messages that tensorflow and its operations were deprecated and to update. Obviously I ignored them, and everything worked.

2) It had an issue creating the thumbnails of the some of the files and would stop the script halfway through. I deleted my images and recreated them, and that solved the problem.

3) Port 5000 was already busy, but changing to 8000 worked fine. Not sure if this is an issue with my machine or not (I'm new at this...)

Again, thanks for the assistance!

**Comment by duhaime** [comment]
Awesome news @agl5000!

Yes, those deprecation warnings spring from tensorflow but are innocuous.

There are a few reasons why some images might not be processable. Removing the wonky images is a fine solution.

It's totally okay to run the local server on any port you like!

I'm glad you got this all straightened out. Is it alright to close this issue in that case?

**Comment by agl5000** [comment]
Yep--thanks again!
