### ISSUE TITLE
Consider multi-threaded thumbnail generation

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/pix-plot#8]
Would it be possible to do multithreaded thumbnail creation, either natively via a python pool or possibly via gnu parallel?

**Comment by duhaime** [comment]
Yes, this is a good idea. I just merged a branch that should implement this behavior. I have had a heck of a time working with `pathos` (a branch of the multiprocessing library that can be used in Python classes) in the past, so I just moved the thumbnail generation function outside the main class and used a Pool to keep things simple.

**Comment by pleonard212** [comment]
Wonderful!
