### ISSUE TITLE
Upgrade greyscale images to 3-channel RGB?

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/pix-plot#82]
Some digitized collections of images are in 8-bit greyscale (0-255, 1 channel) jpeg format. The libraries we use tend to flail with a "unexpected data shape" error in this case, since they expect 3-channel RGB.  I suspect many folks won't know how to fix the problem, due to the obtuse TF error message.  I believe PIL can non-destructively convert to RGB (in the sense of it won't harm existing color images) with `img.convert("RGB")` or similar...

Such conversions just duplicate the single grey ramp into all 3 color channels, so there's no information loss or judgement call required...

**Comment by pleonard212** [comment]
I think the latest image processing pipeline in the experimental branch solves this.

**Comment by duhaime** [comment]
ah yes, the [`load_img` method from `keras_preprocessing.image.utils`](https://github.com/keras-team/keras-preprocessing/blob/master/keras_preprocessing/image/utils.py) takes care of this!
