### ISSUE TITLE
unrecognized arguments

### ISSUE THREAD

**Issue by cncoleman** [YaleDHLab/pix-plot#88]
Loading the directory of images that worked on the master branch does not work with experimental. It throws the error "unrecognized arguments."

**Comment by duhaime** [comment]
Ah yes, the data structure has changed entirely between master and experimental to improve performance and enable transitions.

To use the experimental viewer, you'll need to process your data with the experimental branch as well...

**Comment by duhaime** [comment]
@cncoleman Sorry, I think I misread your comment at first! Did you wrap the file glob in double quotes? That should set all to right:

```bash
pip install pixplot -U
pixplot --images "my_cats/*.jpg"
```

How does that sound?

**Comment by duhaime** [comment]
@cncoleman is it safe to close this issue out? If not I'm happy to follow up on this!

**Comment by cncoleman** [comment]
Yes!
