### ISSUE TITLE
Rendered image size

### ISSUE THREAD

**Issue by bado-lee** [YaleDHLab/pix-plot#93]
Thanks for the great application.
I have a quick question.
Is it possible to adjust image size of each data point?
Currently Im rendering about only 200 data points with very small resolutions. Distances for each data points are quite far apart so there are mostly black spaces in the screen.
Id really appreciate your help.

**Comment by bado-lee** [comment]
Oh... I've just checked experimental branch and it has what I've just needed.
Just one more question,
If I wanted to plugin my custom clustering method other than umap, tsne...
Would there be specific commit that I can get idea from?
Thank you in advance.

**Comment by duhaime** [comment]
@bado-lee Thanks for your note. It's possible you figured this out already, but just in case https://github.com/YaleDHLab/pix-plot/blob/experimental/pixplot/pixplot.py#L340 is the function that returns the layout options. Check out what happens in that function to see how the layouts are created and stored.

The only hitch with a custom layout is currently there are distinct icons for the client side layout options (grid, umap, rasterfairy). Presently, you'd have to add a little icon to the client side code to achieve your layout. Soon it will be easier to create custom layouts client side, so stay tuned!

**Comment by bado-lee** [comment]
Thanks a lot!! :)
