### ISSUE TITLE
Use custom feature set for images?

### ISSUE THREAD

**Issue by genec1** [YaleDHLab/pix-plot#97]
Is there a way to use custom features as the basis for the clustering?  Specifically, I have a trained CNN trained on my images and I'd like to use weights from the last NN layer as input into the UMAP projection.

**Comment by duhaime** [comment]
@genec1 this is something we've been thinking a little about. At the moment, one can hack this into place, but it takes a little doing. Specifically one could:

1. create a plot without your custom layout
2. examine `./output/data/imagelists/imagelist-{{ hash }}.json` Specifically check out the value of the `images` key.
3. in a custom script sort your images into the image order in step 2, then vectorize your images with [something like this](https://github.com/YaleDHLab/pix-plot/blob/master/pixplot/pixplot.py#L373) (assuming your model is from Keras). Then you'll have a matrix with shape n,k where n is the number of images in your dataset and k is the dimensionality returned by the model.
4. run umap on the projection and save a new file `./output/data/layouts/my-layout.json`
5. add your layout to the list of available layouts in `./output/data/manifest.json` (see the `layouts` key).
6. load the plot and trigger the requested layout in the console with `layout.set('x')` where `x` is the name of your layout in the manifest file (e.g. 'tsne', 'umap', 'grid', ....)

That's a bunch of work for a custom layout though! We could make this much easier for users by consuming the path to a persisted model and the name of a layer to sample from. Maybe there'd be another flag that would use the model output without projection -- e.g. if the user provided a model that returns rgb vals for an image, we don't need to project the output down to a lower dimensionality.

In any event, if you have notions on how this kind of functionality could be exposed to users in a seamless fashion, I'm all ears!

**Comment by genec1** [comment]
Thanks for the detailed reply.  Ideally, along with the images I'd provide a matrix of n samples x m features.  That gives me the maximum amount of flexibility -- the features can be extracted from an NN layer or from any other custom data source/processing I may be doing.

**Comment by duhaime** [comment]
I like that--it's even simpler than the user providing a model specifying a layer to sample. 

We're working on a lightbox view for selected images right now but once that's wrapped I'll take a look at this. If you'd want to try out a pull request in the interim that'd be awesome. Strictly if you're interested and available...

**Comment by genec1** [comment]
>  If you'd want to try out a pull request in the interim that'd be awesome.

I'd love to but I barely have enough time for my primary project right now!  But am happy to test any code if/when you have something to try out.

**Comment by duhaime** [comment]
Roger that. I'll ping you once there's something to try out...

**Comment by ed-fish** [comment]
Not sure if this helps - But I am just creating an image folder and outputting my embeddings to np files with the same name as the image list '*.jpg.npy'. Then create an output dir with just the image-vector folder containing the embeddings and run with `--use-cache`. Seems to be working great but may have misunderstood the question.

**Comment by duhaime** [comment]
That's a clever workaround!

**Comment by ed-fish** [comment]
If you like I could update the README with a detailed description for using your own embeddings. I also have a fork of the project that can display video and audio previews for multi-modal embeddings if that is of interest.
